### ISSUE TITLE
Caching and computing timestamps

### ISSUE THREAD

**Issue by albertmeronyo** [King-s-Knowledge-Graph-Lab/ProVe#26]
Show timestamp of when the score was computed by last time in the UI
In the backend, if the compute is recent do not recompute again

**Comment by dignityc** [comment]
The current ProVe gadget displays the request time for each item. 

As for the last point, I'm not sure if it's a good idea to prevent 'recompute' based solely on the processing time, as some users may want to recompute to see changes over a short-term period. How about implementing a rule to prevent recompute if the item has already been processed N times within a specific time window?

**Comment by odinaldo** [comment]
Please follow recommendation 1. on ProVe Issues v3 document.

**Comment by yihang-zhao** [comment]
Now the estimated computation time will be displayed based on the references number
