### ISSUE TITLE
Add documentation about non-wikimedia site requests

### ISSUE THREAD

**Issue by albertmeronyo** [King-s-Knowledge-Graph-Lab/ProVe#28]
From Nikki via WD Telegram: looking at the code, I see that it makes requests to non-wikimedia sites. that's generally considered a privacy and security issue and you should avoid it as much as possible (e.g. upload any images it requires to commons), and where it's not possible to avoid it, you should make it clear in the installation instructions and the header of the script

**Comment by dignityc** [comment]
ProVe will scrape web documents via reference URLs but will not store them anywhere. I will add a comment in the script to clarify this issue.

**Comment by dignityc** [comment]
Updated in the last paragraph of Introduction in the ProVe page: https://www.wikidata.org/wiki/Wikidata:ProVe#Introduction. Please review this.

**Comment by albertmeronyo** [comment]
Now fixed, thanks
