### ISSUE TITLE
Score Calculation

### ISSUE THREAD

**Issue by odinaldo** [King-s-Knowledge-Graph-Lab/ProVe#36]
1. Claims without reference should be included in the score calculation. These are items for which the user needs to add references. They should be part of the total items and count as zero in the numerator.
2. Inaccessible references should be treated as NEIs, i.e., we cannot assess whether they support or attack its claim, so best to treat them as such. Later on, we can find better ways to provide a more meaningful score.
3. The score formula should be simplified in the page since multiplication by zero is zero. So the score can be more simply stated as (N(Supports) -N(Refutes))/N(Total). Here N(Total) is really total (see 1. above).

**Comment by dignityc** [comment]
New formula has been updated ( (N(Supports) -N(Refutes))/N(Total), N(Total): only the number of 'external references' )
